config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'users', to: 'users#index'
  get 'users/:id', to: 'users#show', as: 'user'
  get 'users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get 'users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post'
  get 'users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
  post 'users/:user_id/posts', to: 'posts#create', as: 'create_user_post'

  resources :posts, only: %i[new create] do
    post 'create_comment', on: :member
  end

  resources :comments, only: %i[new create]
  resources :users do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  def self.update_comments_counter(post_id)
    post = Post.find(post_id)
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  def update_likes_counter
    post.update(likes_counter: post.likes.size)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes, foreign_key: :post_id

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.update_posts_counter(author_id)
    author = User.find(author_id)
    author.posts.increment!(:comments_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @user_posts = @user.posts.includes(:comments).order(created_at: :desc)
    @recent_comments = @user_posts.flat_map(&:recent_comments)
  end

  def show
    @user = User.find(params[:user_id])
    @user_post = @user.posts.find(params[:id])
    @post_index = @user.posts.order(created_at: :desc).pluck(:id).index(@user_post.id) + 1
    @likes_count = @user_post.likes_counter
    @comments_count = @user_post.comments_counter
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to user_posts_url(user_id: @post.author_id)
    else
      render :new
    end
  end

  def create_comment
    @user_post = Post.find(params[:id])
    @comment = @user_post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(user_id: @user_post.author_id, id: @user_post.id), notice: 'Comment created successfully.'
    else
      redirect_to user_post_path(user_id: @user_post.user.id, id: @user_post.id), alert: 'Failed to create comment.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :comments_counter, :likes_counter)
  end

  def comment_params
    params.require(:comment).permit(:post_id, :text)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    super do |resource|
      BackgroundWorker.trigger(resource)
    end
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_posts = @user.posts.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'users_styles' %>
<div>
  <ul>
    <li><img src="<%= @user.photo %>"></li>
    <div class="border">
      <li><%= @user.name %></li>
      <li>Number of posts: <%= @user.posts_counter %></li>
    </div>
  </ul>
  <!--Bio section part-->
  <div class="bio">
    <h2>Bio</h2>
    <%= @user.bio %>
  </div>
  <div class="post">
    <% @user_posts.each_with_index do |post, index| %>
      <%= link_to user_post_path(@user,post.id) do %>
        <h3>Post <%= index+1 %></h3>
      <% end %>
      <%= post.text %>
      <p>Comments: <%= post.comments_counter %> || Likes: <%= post.likes_counter %></p>
    <% end %>
  </div>
  <div class="comments">
    <% @recent_comments.each do |comment| %>
      <p><span><%= comment.author.name %></span>: <%= comment.text %></p>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_with(model: @post, url: user_posts_path(user_id: current_user.id), class: 'post-form') do |form| %>
  <h2>Add User Post</h2>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: 'Enter your title', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_field :text, placeholder: 'Enter your text', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :comments_counter %>
    <%= form.number_field :comments_counter, placeholder: 'Enter number of comments', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :likes_counter %>
    <%= form.number_field :likes_counter, placeholder: 'Enter number of likes', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit "Create Post", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="post_comments"><div class="comments">
  <div class="post_header">
    <span>Post: <%= @user_post.id %> by <%= @user_post.author.name %></span>
    <span>Comments: <%= @comments_count %> || Likes: <%= @likes_count %></span>
    <p>
     <%= @user_post.text %>
    </p>
  </div>
</div>
<div class="comments">
  <% @user_post.comments.each do |comment| %>
    <p><span><%= comment.author.name %></span>: <%= comment.text %></p>
  <% end %></div>
 <!-- Form to Add new comment -->
  <div class="form">
  <h1>Add post comment</h1>
    <%= form_with(model: @comment, url: create_comment_post_path(@user_post, @comment.post_id)) do |form| %>

      <div class="comment_input"><%= form.text_area :text, placeholder: 'Enter your comment' %></div>
      <%= form.submit 'Post Comment' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'users_styles' %>
<div>
  <% @users.each do |user| %>
    <ul>
      <li><img src=<%= user.photo %>></li>
      <div class="border"> 
        <li><%= link_to user.name, user_path(user) %></li>
        <li>Number of posts <%= user.posts_counter %></li>
      </div>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'users_styles' %>
<div>
  <ul>
    <li><img src="<%= @user.photo %>"></li>
    <div class="border">
      <li><%= @user.name %></li>
      <li>Number of posts: <%= @user.posts_counter %></li>
    </div>
   
  </ul>
  <!--Bio section part-->
   <div class="bio">
    <h2>Bio</h2>
    <%= @user.bio%>
    </div>
    
    <%@user_posts.each_with_index do |post, index|%>
    <div class="post">
    <h2>post <%=index+1%></h2>
    <%=post.text %>
    <p>Comments:<%=post.comments_counter %>||
    Likes:<%=post.likes_counter %>
    </p>

    
    </div>
    <%end%>
   <button>
  <%= link_to "See All Posts", user_posts_path(@user) %>
</button>

</div>